### ISSUE TITLE
is your plugin compatible with other sql schemes?

### ISSUE THREAD

**Issue by niksfirefly** [stephanblanke/roundcube-aliases#1]
is your plugin compatible with other sql schemes?
for example
I use custom made exim/sql aliases 

regards

**Comment by stephanblanke** [comment]
Hi,

you can edit the following settings in your config.inc.php to match your database scheme:

```
$rcmail_config['alias_sql_aliases']
$rcmail_config['alias_sql_allaliases']
$rcmail_config['alias_sql_read']
$rcmail_config['alias_sql_update']
$rcmail_config['alias_sql_delete']
$rcmail_config['alias_sql_create']
$rcmail_config['aliases_sql_toggle']
```

These statements are used by the sql driver:
https://github.com/stephanblanke/roundcube-aliases/blob/master/lib/drivers/sql.php#L56

You can find examples in the README file:
https://github.com/stephanblanke/roundcube-aliases/blob/master/README

Best regards
Stephan
